### ISSUE TITLE
Driver directory does not exist.

### ISSUE THREAD

**Issue by Greg-Boggs** [vincenzodibiaggio/drupal8_base#2]
This may be user error on my part, but when I make a services file and run the build, I get this:

  [InvalidArgumentException]  
  The "/core/lib/Drupal/Core/Database/Driver" directory does not exist.

**Comment by Greg-Boggs** [comment]
Miss leading error message below the actual error.

**Comment by vincenzodibiaggio** [comment]
Hi Greg,
if you make an update to your services file, you need to update the build process or the `services` file in the `base_files` directory.

Bye

**Comment by Greg-Boggs** [comment]
In my case, the actual problem was that I hadn't set the webroot to web and I hadn't set the db type correctly. This is the error you get when there's an issue with your yml file. It was misleading, but scrolling up shows the really useful error message.

**Comment by vincenzodibiaggio** [comment]
Uhm, I guess that I need to improve the docs. Tnx.

**Comment by therobyouknow** [comment]
Hi Greg. Can you advise how to set the webroot to web? I was searching for a solution to my issue, I eventually discovered myself an alternative solution - https://github.com/hechoendrupal/DrupalConsole/issues/2592#issuecomment-240440662 but I am still curious as to what "setting the webroot to web" means. Does it involve changing a Drupal system variable?

> In my case, the actual problem was that I hadn't set the webroot to web

**Comment by Greg-Boggs** [comment]
It means in your properties.yml file, which is the config key for robo.... set the key for "webroot" to "web".

**Comment by therobyouknow** [comment]
Thanks Greg.
